services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    image: golang:1.24
    container_name: app
    restart: always
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
    depends_on:
      - mysql
      - rabbitmq
    command: sh -c "cd cmd/ordersystem && go run ."
    volumes:
      - .:/app
    working_dir: /app